# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serjipe_message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serjipe_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15serjipe_message.proto\"e\n\nDeviceData\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nvalue_name\x18\x03 \x03(\t\x12\r\n\x05value\x18\x04 \x03(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"b\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x19\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x0b.DeviceData\"?\n\x07\x43ommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x11\n\tparameter\x18\x03 \x01(\t\"G\n\x08\x44iscover\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x16\n\x0eport_multicast\x18\x02 \x01(\x05\x12\x17\n\x0fport_udp_sensor\x18\x03 \x01(\x05\"B\n\x12ListarDispositivos\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x1c\n\x07\x64\x65vices\x18\x02 \x03(\x0b\x32\x0b.DeviceInfo\"\xd9\x01\n\x08\x45nvelope\x12\x1d\n\x08\x64iscover\x18\x01 \x01(\x0b\x32\t.DiscoverH\x00\x12\x1b\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x08.CommandH\x00\x12\"\n\x0b\x64\x65vice_data\x18\x03 \x01(\x0b\x32\x0b.DeviceDataH\x00\x12\"\n\x0b\x64\x65vice_info\x18\x04 \x01(\x0b\x32\x0b.DeviceInfoH\x00\x12\x32\n\x13listar_dispositivos\x18\x05 \x01(\x0b\x32\x13.ListarDispositivosH\x00\x12\x0c\n\x04\x65rro\x18\x06 \x01(\tB\x07\n\x05\x63\x61rgab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serjipe_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEDATA']._serialized_start=25
  _globals['_DEVICEDATA']._serialized_end=126
  _globals['_DEVICEINFO']._serialized_start=128
  _globals['_DEVICEINFO']._serialized_end=226
  _globals['_COMMAND']._serialized_start=228
  _globals['_COMMAND']._serialized_end=291
  _globals['_DISCOVER']._serialized_start=293
  _globals['_DISCOVER']._serialized_end=364
  _globals['_LISTARDISPOSITIVOS']._serialized_start=366
  _globals['_LISTARDISPOSITIVOS']._serialized_end=432
  _globals['_ENVELOPE']._serialized_start=435
  _globals['_ENVELOPE']._serialized_end=652
# @@protoc_insertion_point(module_scope)
